apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: jrdckrhub/api-conversao:0.0.1
          ports:
            - containerPort: 8080            #A mesma que foi exposta no Dockerfile para gerar a imagem

---                                          ## (ou service.yaml)
apiVersion: v1
kind: Service
metadata:
  name: api-conversao-service
spec:
  selector:
      app: api-conversao
  ports: 
    - port: 8080             # Porta do serviço web <porta exposta>        Ex: 8080:8080
      targetPort: 8080       # porta do container(Container Port)  #Sevice NodePort
  type: NodePort

